# NumPy

+ Install numpy

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


+ Import numpy

In [6]:
import numpy as np

THE BASICS

In [7]:
a=np.array([2,3,6,8,1])
print(a)

[2 3 6 8 1]


In [9]:
b=np.array([[3.0,35.3,1.34],[5.3,214.1,14.1]])
print(b)

[[  3.    35.3    1.34]
 [  5.3  214.1   14.1 ]]


In [10]:
# Get Dimension of a np.array
a.ndim

1

In [11]:
b.ndim

2

In [21]:
c=np.array([[[23,21,41],[31,643,74.2],[12,523,52]]])
print(c)

[[[ 23.   21.   41. ]
  [ 31.  643.   74.2]
  [ 12.  523.   52. ]]]


In [13]:
c.ndim

3

In [14]:
# Get shape
c.shape

(1, 3, 3)

In [15]:
b.shape

(2, 3)

In [16]:
a.shape

(5,)

In [17]:
# Get the tpye
a.dtype

dtype('int32')

In [18]:
b.dtype

dtype('float64')

In [22]:
c.dtype

dtype('float64')

In [24]:
# Specified the type of an array
d=np.array([[2,4,4],[4,7,9]], dtype='int16')
print(d)

[[2 4 4]
 [4 7 9]]


In [25]:
d.dtype

dtype('int16')

In [32]:
# Get size 'depending the dtype of the array'
a.itemsize

4

In [27]:
d.itemsize

2

In [31]:
# Get total size 'number of elements'
a.size

5

In [29]:
d.size

6

In [30]:
c.size

9

In [33]:
# Number of bytes
a.itemsize * a.size

20

In [34]:
a.nbytes

20

+ CHANGING SPECIFIC ELEMENTS, COLS, ROWS, ETC


In [35]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
# Get an specific element [r,c]
a[1,1]

7

In [40]:
# Using the negative notation
a[-1,-4]

7

In [41]:
# Get an specific row
a[1, : ]

array([ 6,  7,  8,  9, 10])

In [42]:
# Get a number segment of a specific row
a[0, 1:4]

array([2, 3, 4])

In [43]:
a[1, : ]

array([ 6,  7,  8,  9, 10])

In [60]:
# Get an specific column
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
a[:, 2]

array([3, 8])

In [63]:
# Getting a little more fancy [startindex:endindex:stepsize]
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [71]:
arr[0, 0:7:2]

array([1, 3, 5, 7])